name = "derived"
description = "The gleam code generator's code generator"
version = "0.2.0"
licenses = ["Apache-2.0"]
repository = { type = "github", user = "dusty-phillips", repo = "derived" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
glexer = ">= 2.2.1 and < 3.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
